# Generated by Django 5.0.1 on 2026-06-11 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answer', models.SmallIntegerField()),
                ('correct', models.BooleanField()),
                ('response_ms', models.PositiveIntegerField()),
                ('scaffold_shown', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('points', models.PositiveIntegerField(default=0)),
                ('questions', models.PositiveIntegerField(default=0)),
                ('goal_met', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('add', 'Addition'), ('sub', 'Subtraction')], max_length=3)),
                ('a', models.PositiveSmallIntegerField()),
                ('b', models.PositiveSmallIntegerField()),
                ('answer', models.PositiveSmallIntegerField()),
                ('strategy', models.CharField(max_length=32)),
                ('stage', models.PositiveSmallIntegerField(db_index=True)),
            ],
            options={
                'ordering': ['stage', 'operation', 'a', 'b'],
            },
        ),
        migrations.CreateModel(
            name='FactProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.PositiveSmallIntegerField(default=0)),
                ('scaffold', models.PositiveSmallIntegerField(default=2)),
                ('scaffold_streak', models.PositiveSmallIntegerField(default=0)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('introduced_at', models.DateTimeField()),
                ('streak', models.PositiveSmallIntegerField(default=0)),
                ('lapses', models.PositiveSmallIntegerField(default=0)),
                ('ema_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('mastered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='pirate', max_length=32)),
                ('daily_goal_points', models.PositiveSmallIntegerField(default=150)),
            ],
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.UniqueConstraint(fields=('operation', 'a', 'b'), name='unique_fact'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drill.fact'),
        ),
        migrations.AddField(
            model_name='factprogress',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drill.fact'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='drill.student'),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='drill.student'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='drill.student'),
        ),
        migrations.AddConstraint(
            model_name='factprogress',
            constraint=models.UniqueConstraint(fields=('student', 'fact'), name='unique_student_fact'),
        ),
        migrations.AddConstraint(
            model_name='dailyprogress',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_student_date'),
        ),
    ]
