# Generated by Django 5.0.1 on 2026-06-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='seen_instructions',
            field=models.BooleanField(default=False),
        ),
    ]
