# Generated by Django 5.0.1 on 2026-06-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0002_student_seen_instructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={'ordering': ['intro_order']},
        ),
        migrations.AddField(
            model_name='fact',
            name='intro_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
