# Generated by Django 5.0.1 on 2026-06-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0003_alter_fact_options_fact_intro_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='custom_selection',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
