# Generated by Django 5.0.1 on 2026-09-10 13:00

import drill.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0004_student_custom_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='operations',
            field=models.JSONField(blank=True, default=drill.models.default_operations),
        ),
        migrations.AlterField(
            model_name='fact',
            name='operation',
            field=models.CharField(choices=[('add', 'Addition'), ('sub', 'Subtraction'), ('mul', 'Multiplication'), ('div', 'Division')], max_length=3),
        ),
    ]
