# Generated by Django 5.0.1 on 2026-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0005_student_operations_alter_fact_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='factprogress',
            name='known_on_sight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='reach',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
