# Generated by Django 5.0.1 on 2026-09-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0006_factprogress_known_on_sight_student_reach'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='recent_misses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
