# Generated by Django 5.0.1 on 2026-09-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drill', '0007_student_recent_misses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='given_answer',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
